[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Arbitrum RPC endpoints
[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://arbitrum-sepolia.gateway.tenderly.co"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
